### ISSUE TITLE
Clean up AppVeyor

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic.covrpage#3]
Looks like AppVeyor still thinks this is a different repo: https://ci.appveyor.com/project/ropensci/tic-covrpage.

@maelle: Could you please take a look?

**Comment by maelle** [comment]
We might need to keep it under the original Appveyor account /set up a new project? Cc @sckott

**Comment by pat-s** [comment]
Everything seems alright? Can you give me a detailed heads-up whats wrong?

There is only one repo that can be enabled in the Appveyor ropensci acc and this one is on.

**Comment by sckott** [comment]
yep, it's turned on, looks like the badge is `[![Build status](https://ci.appveyor.com/api/projects/status/doi445itxmrgomn7?svg=true)](https://ci.appveyor.com/project/ropensci/tic-covrpage-sfcba)`

**Comment by pat-s** [comment]
Cleaned up. Appveyor is strange sometimes as it makes it possible to enable a project multiple times in some cases which might result in a weird chr/num suffix then.
