### ISSUE TITLE
Covrpage badge

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic.covrpage#4]
@yonicd What is the current approach for a covrpage badge in the README? The current one is broken.

**Comment by yonicd** [comment]
that api link was a test case in heroku that caused problems because it wasnt up unless heroku was pinged. 

i'll switch it back to static, which is just running `covrpage::make_badge()` and pasting the output into the root readme

**Comment by yonicd** [comment]
fixed https://github.com/ropenscilabs/tic.covrpage/commit/a54cbeb343fa05803e95b12ee3eaff06587852df
