### ISSUE TITLE
appveyor is being ignored

### ISSUE THREAD

**Issue by yonicd** [ropenscilabs/tic.covrpage#6]
is appveyor turned off deliberately for this repo?

**Comment by pat-s** [comment]
We no longer check any tic related repo on appveyor. GHA only.

**Comment by yonicd** [comment]
Ah ok. Should i add gha files?

**Comment by pat-s** [comment]
All other example tic repos only build on Travis for now. It's sufficient for us but you are of course free to add more to the bag :)
